<?php

    /* OSWA Codeine
     * @author BreathLess
     * @type Codeine Driver
     * @description: 
     * @package Codeine
     * @subpackage Drivers
     * @version 5.0
     * @date 28.03.11
     * @time 2:23
     */

    self::Fn('Generate', function ($Call)
    {
        return '# Autogenerated by Codeine
<VirtualHost *:80>
   DocumentRoot "'.Root.'"
   ServerName '.$Call['Host'].'

   # This should be omitted in the production environment
   SetEnv Environment development

   <Directory "'.Root.'">
       Options Indexes MultiViews FollowSymLinks
       AllowOverride All
       Order allow,deny
       Allow from all
   </Directory>

</VirtualHost>';});
