<?php

    /* Codeine
     * @author BreathLess
     * @description: 
     * @package Codeine
     * @version 6.0
     * @date 28.03.11
     * @time 2:23
     */

    self::Fn('Generate', function ($Call)
    {
        // TODO Codeinize
        return '# Autogenerated by Codeine
<VirtualHost *:80>
   DocumentRoot "'.$Call['Path'].'"
   ServerName '.$Call['Host'].'

   # This should be omitted in the production environment
   SetEnv Environment development

   <Directory "'.$Call['Path'].'">
       Options Indexes MultiViews FollowSymLinks
       AllowOverride All
       Order allow,deny
       Allow from all
   </Directory>

</VirtualHost>';});
